apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: naveen  
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: naveen012/mypython:v1
        ports:
        - containerPort: 8080
