apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: naveen
  labels:
    name: python
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      name: python
  selector:
    name: python-deployment
